package th.co.ais.mimo.debt.exempt.repo;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.jpa.repository.query.Procedure;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import th.co.ais.mimo.debt.exempt.dto.GetRefAssignDto;
import th.co.ais.mimo.debt.exempt.entity.DccCriteriaMaster;
import th.co.ais.mimo.debt.exempt.entity.DccCriteriaMasterId;
import th.co.ais.mimo.debt.exempt.model.DMSEM004CriteriaMasterDto;
import th.co.ais.mimo.debt.exempt.model.DMSEM004GetBaByMobileNumDto;

@Repository
public interface DMSEM004CriteriaMasterRepo extends JpaRepository<DccCriteriaMaster, DccCriteriaMasterId> {

	@Query(value = "  SELECT criteria_id AS criteriaId,   "
			+ "       criteria_type AS criteriaType,    "
			+ "       criteria_description AS criteriaDescription,   "
			+ "       company_code AS companyCode,  "
			+ "       collection_segment_list AS collectionSegmentList,   "
			+ "       payment_type_list AS paymentTypeList,   "
			+ "       bill_cycle_list AS billCycleList,  "
			+ "       region_list AS regionList,   "
			+ "       mobile_status_list AS mobileStatusList,   "
			+ "       product_group_list AS productGroupList,   "
			+ "       cate_subcate_list AS cateSubcateList,  "
			+ "       ba_status_list AS baStatusList,   "
			+ "       min_invoice_mny AS minInvoiceMny,   "
			+ "       invoice_count AS invoiceCount,  "
			+ "       debt_mny_from AS debtMnyFrom,   "
			+ "       debt_mny_to AS debtMnyTo,   "
			+ "       ar_mny_from AS arMnyFrom,   "
			+ "       ar_mny_to AS arMnyTo,  "
			+ "       debt_age_from AS debtAgeFrom,   "
			+ "       debt_age_to AS debtAgeTo,   "
			+ "       credit_term_flag AS creditTermFlag,   "
			+ "       status_age_from AS statusAgeFrom,   "
			+ "       status_age_to AS statusAgeTo,   "
			+ "       service_age_from AS serviceAgeFrom,   "
			+ "       service_age_to AS serviceAgeTo,  "
			+ "       TO_CHAR(first_ar_dat_from, 'YYYY/MM/DD') AS firstArDatFrom,   "
			+ "       TO_CHAR(first_ar_dat_to, 'YYYY/MM/DD') AS firstArDatTo,  "
			+ "       TO_CHAR(ba_inactive_dat_from, 'YYYY/MM/DD') AS baInactiveDatFrom,   "
			+ "       TO_CHAR(ba_inactive_dat_to, 'YYYY/MM/DD') AS baInactiveDatTo,  "
			+ "       status_reason_list AS statusReasonList,   "
			+ "       action_reason_list AS actionReasonList,   "
			+ "       nego_flag AS negoFlag,   "
			+ "       exempt_flag AS exemptFlag,   "
			+ "       max_account AS maxAccount,   "
			+ "       max_amount AS maxAmount,  "
			+ "       assign_duration AS assignDuration,   "
			+ "       campaign_code AS campaignCode,  "
			+ "       agent_type AS agentType,   "
			+ "       assign_type AS assignType,    "
			+ "       assign_job AS assignJob,   "
			+ "       due_day AS dueDay,   "
			+ "       call_type AS callType,   "
			+ "       message_id AS messageId,   "
			+ "       max_call AS maxCall,   "
			+ "       max_redial AS maxRedial,  "
			+ "       template_id AS templateId,   "
			+ "       TO_CHAR(check_dat_from, 'YYYY/MM/DD') AS checkDatFrom,   "
			+ "       TO_CHAR(check_dat_to, 'YYYY/MM/DD') AS checkDatTo,  "
			+ "       TO_CHAR(invoice_back_dat, 'YYYY/MM/DD') AS invoiceBackDat,   "
			+ "       invoice_interval AS invoiceInterval,  "
			+ "       run_type AS runType,   "
			+ "       run_at AS runAt,   "
			+ "       run_bill_type AS runBillType,   "
			+ "       run_bill_day AS runBillDay,  "
			+ "       TO_CHAR(run_start_dat, 'YYYY/MM/DD') AS runStartDat,   "
			+ "       TO_CHAR(run_end_dat, 'YYYY/MM/DD') AS runEndDat,   "
			+ "       auto_assign_flag AS autoAssignFlag,   "
			+ "       last_update_by AS lastUpdateBy,  "
			+ "       TO_CHAR(last_update_dtm, 'YYYY/MM/DD HH24:Mi:SS') AS lastUpdateDtm,  "
			+ "       order_level AS orderLevel,   "
			+ "       priority_no AS priorityNo,  "
			+ "       blacklist_type AS blacklistType,   "
			+ "       blacklist_subtype AS blacklistSubtype,   "
			+ "       letter_level AS letterLevel,  "
			+ "       letter_address_type AS letterAddressType,   "
			+ "       TO_CHAR(letter_dat, 'YYYY/MM/DD') AS letterDat,   "
			+ "       letter_payment_due AS letterPaymentDue,   "
			+ "       province_list AS provinceList,   "
			+ "       tp_debt_type AS tpDebtType,  "
			+ "       value_segment_list AS valueSegmentList,   "
			+ "       order_type AS orderType,   "
			+ "       reason_code_list AS reasonCodeList,   "
			+ "       TO_CHAR(df_dat_from, 'YYYY/MM/DD') AS dfDatFrom,  "
			+ "       TO_CHAR(df_dat_to, 'YYYY/MM/DD') AS dfDatTo,   "
			+ "       blacklist_dat_flag AS blacklistDatFlag,  "
			+ "       TO_CHAR(blacklist_dat_from, 'YYYY/MM/DD') AS blacklistDatFrom,   "
			+ "       TO_CHAR(blacklist_dat_to, 'YYYY/MM/DD') AS blacklistDatTo,  "
			+ "       ca_status AS caStatus,   "
			+ "       TO_CHAR(ca_inactive_dat_from, 'YYYY/MM/DD') AS caInactiveDatFrom,   "
			+ "       TO_CHAR(ca_inactive_dat_to, 'YYYY/MM/DD') AS caInactiveDatTo,  "
			+ "       thai_letter_flag AS thaiLetterFlag,   "
			+ "       inc_envelope_flag AS incEnvelopeFlag,   "
			+ "       template_id_ctype AS templateIdCtype,   "
			+ "       super_deal_flag AS superDealFlag,   "
			+ "       fix_company_type_flag AS fixCompanyTypeFlag,   "
			+ "       device_discount_from AS deviceDiscountFrom,   "
			+ "       device_discount_to AS deviceDiscountTo,   "
			+ "       create_by AS createBy,   "
			+ "       ca_debt_mny_from AS caDebtMnyFrom,   "
			+ "       ca_debt_mny_to AS caDebtMnyTo,  "
			+ "       gen_detail_rpt_flag AS genDetailRptFlag,   "
			+ "       bill_system_list AS billSystemList,   "
			+ "       auto_sms_flag AS autoSmsFlag,   "
			+ "       ca_device_discount_from AS caDeviceDiscountFrom,   "
			+ "       ca_device_discount_to AS caDeviceDiscountTo,  "
			+ "       cpe_brand_list AS cpeBrandList,   "
			+ "       cpe_flag AS cpeFlag,   "
			+ "       ivr_robot_flag AS ivrRobotFlag,   "
			+ "       cpe_penalty_flag AS cpePenaltyFlag,   "
			+ "       cpe_penalty_amount AS cpePenaltyAmount,  "
			+ "       bundling_flag AS bundlingFlag,   "
			+ "       ca_amount_flag AS caAmountFlag,   "
			+ "       ca_amount AS caAmount   "
			+ " FROM dcc_criteria_master "
			+ " where mode_id = :modeId  "
			+ " AND  criteria_id = :criteriaId "
			+ " AND  CRITERIA_DESCRIPTION LIKE :description "
			+ " order by last_update_dtm desc ", nativeQuery = true)
	DMSEM004CriteriaMasterDto  SerachData(@Param("modeId") String modeId,
			@Param("criteriaId") Long criteriaId,
			@Param("description") String description );
	
	@Modifying
	@Query(value = " update dcc_criteria_master set run_end_dat = trunc(SYSDATE), "
    		+ "     last_update_by = :lastUpdateBy , last_update_dtm = sysdate, blacklist_dat_flag = :blacklistDatFlag , "
    		+ "     blacklist_dat_from = to_date(:blacklistDatFrom,'YYYY/MM/DD'), blacklist_dat_to = to_date(:blacklistDatTo,'YYYY/MM/DD') "
    		+ "     where mode_id = :modeId "
    		+ "		and criteria_id = :criteriaId "
    		+ "		and criteria_type = :criteriaType " , nativeQuery = true)
    void updateCriteriaInfo( @Param("lastUpdateBy") String lastUpdateBy, 
                       @Param("blacklistDatFlag") String blacklistDatFlag, 
                       @Param("blacklistDatFrom") String blacklistDatFrom, 
                       @Param("blacklistDatTo") String blacklistDatTo, 
                       @Param("modeId") String modeId, 
                       @Param("criteriaId") Long criteriaId, 
                       @Param("criteriaType") String criteriaType);
	
	@Modifying
	@Query(value = " delete from {h-schema}dcc_criteria_master  where criteria_id = :criteriaId and mode_id = :modeId " , nativeQuery = true)
    void deleteCriteriaInfo(@Param("modeId")String modeId, @Param("criteriaId") Long criteriaId);
	
	@Query(value = " SELECT mode_id AS modeId, "
			+ "       preassign_id AS preassignId, "
			+ "       criteria_id AS criteriaId, "
			+ "       criteria_type AS criteriaType, "
			+ "       preassign_dat AS preassignDat,"
			+ "       assign_id AS assignId, "
			+ "       assign_dat AS assignDat, "
			+ "       assign_status AS assignStatus, "
			+ "       unassign_dat AS unassignDat, "
			+ "       company_code AS companyCode, "
			+ "       collection_segment_list AS collectionSegmentList, "
			+ "       payment_type_list AS paymentTypeList,"
			+ "       bill_cycle_list AS billCycleList, "
			+ "       region_list AS regionList, "
			+ "       mobile_status_list AS mobileStatusList, "
			+ "       product_group_list AS productGroupList, "
			+ "       cate_subcate_list AS cateSubcateList, "
			+ "       ba_status_list AS baStatusList,"
			+ "       min_invoice_mny AS minInvoiceMny, "
			+ "       invoice_count AS invoiceCount, "
			+ "       debt_mny_from AS debtMnyFrom, "
			+ "       debt_mny_to AS debtMnyTo, "
			+ "       ar_mny_from AS arMnyFrom, "
			+ "       ar_mny_to AS arMnyTo, "
			+ "       debt_age_from AS debtAgeFrom,"
			+ "       debt_age_to AS debtAgeTo, "
			+ "       credit_term_flag AS creditTermFlag, "
			+ "       status_age_from AS statusAgeFrom, "
			+ "       status_age_to AS statusAgeTo, "
			+ "       service_age_from AS serviceAgeFrom, "
			+ "       service_age_to AS serviceAgeTo, "
			+ "       first_ar_dat_from AS firstArDatFrom, "
			+ "       first_ar_dat_to AS firstArDatTo, "
			+ "       ba_inactive_dat_from AS baInactiveDatFrom, "
			+ "       ba_inactive_dat_to AS baInactiveDatTo, "
			+ "       status_reason_list AS statusReasonList, "
			+ "       action_reason_list AS actionReasonList, "
			+ "       nego_flag AS negoFlag,"
			+ "       exempt_flag AS exemptFlag, "
			+ "       max_account AS maxAccount, "
			+ "       max_amount AS maxAmount, "
			+ "       assign_duration AS assignDuration, "
			+ "       assign_type AS assignType, "
			+ "       agent_type AS agentType, "
			+ "       campaign_code AS campaignCode,"
			+ "       due_day AS dueDay, "
			+ "       message_id AS messageId, "
			+ "       max_call AS maxCall, "
			+ "       max_redial AS maxRedial, "
			+ "       template_id AS templateId, "
			+ "       check_dat_from AS checkDatFrom, "
			+ "       check_dat_to AS checkDatTo, "
			+ "       invoice_back_dat AS invoiceBackDat, "
			+ "       invoice_interval AS invoiceInterval, "
			+ "       auto_assign_flag AS autoAssignFlag, "
			+ "       last_update_by AS lastUpdateBy, "
			+ "       last_update_dtm AS lastUpdateDtm, "
			+ "       order_level AS orderLevel, "
			+ "       collection_segment_all_flag AS collectionSegmentAllFlag, "
			+ "       mobile_status_all_flag AS mobileStatusAllFlag, "
			+ "       region_all_flag AS regionAllFlag,"
			+ "       product_group_all_flag AS productGroupAllFlag, "
			+ "       cate_subcate_all_flag AS cateSubcateAllFlag, "
			+ "       ba_status_all_flag AS baStatusAllFlag, "
			+ "       action_reason_all_flag AS actionReasonAllFlag,"
			+ "       status_reason_all_flag AS statusReasonAllFlag, "
			+ "       payment_type_all_flag AS paymentTypeAllFlag, "
			+ "       bill_cycle_all_flag AS billCycleAllFlag, "
			+ "       create_dtm AS createDtm, "
			+ "       run_db AS runDb, "
			+ "       '' AS criteriaDescription, "
			+ "       cancel_assign_flag AS cancelAssignFlag, "
			+ "       blacklist_type AS blacklistType, "
			+ "       blacklist_subtype AS blacklistSubtype, "
			+ "       letter_level AS letterLevel, "
			+ "       letter_address_type AS letterAddressType, "
			+ "       letter_dat AS letterDat, "
			+ "       letter_payment_due AS letterPaymentDue, "
			+ "       value_segment_list AS valueSegmentList, "
			+ "       order_type AS orderType, "
			+ "       reason_code_list AS reasonCodeList, "
			+ "       confirm_dat AS confirmDat, "
			+ "       process_status AS processStatus, "
			+ "       df_dat_from AS dfDatFrom, "
			+ "       df_dat_to AS dfDatTo, "
			+ "       ca_inactive_dat_from AS caInactiveDatFrom, "
			+ "       ca_inactive_dat_to AS caInactiveDatTo, "
			+ "       NULL AS callType, "
			+ "       assign_job AS assignJob, "
			+ "       province_list AS provinceList, "
			+ "       '' AS cnFlag, "
			+ "       company_type_list AS companyTypeList, "
			+ "       template_id_ctype AS templateIdCtype, "
			+ "       super_deal_flag AS superDealFlag,  "
			+ "       fix_company_type_flag AS fixCompanyTypeFlag,  "
			+ "       device_discount_from AS deviceDiscountFrom, "
			+ "       device_discount_to AS deviceDiscountTo,  "
			+ "       bill_system_list AS billSystemList,  "
			+ "       create_by AS createBy,  "
			+ "       gen_detail_rpt_flag AS genDetailRptFlag,  "
			+ "       cpe_brand_list AS cpeBrandList,  "
			+ "       cpe_flag AS cpeFlag,  "
			+ "       exempt_reason AS exemptReason,  "
			+ "       bundling_flag AS bundlingFlag,"
			+ "		(select reason_description from dcc_reason"
			+ "		where reason_type = 'EXEMPT_ADD' and reason_subtype like 'EXEMPT_ADD' AND REASON_CODE = ACTION_REASON_LIST) AS actionReasonListDesc ,"
			+ "			(select  distinct keyword_desc  from dcc_global_parameter where section_name = 'CRITERIA' and keyword = 'MODULE_CODE' AND KEYWORD_VALUE = assign_Type) AS assignTypeDesc  ,"
			+ "		(select distinct keyword_desc from dcc_global_parameter where section_name = 'CRITERIA' and keyword = 'EXEMPT_LEVEL' AND KEYWORD_VALUE = order_Level) AS orderLevelDesc "
			+ "  FROM dcc_criteria_history  "
			+ "  where mode_id = 'EM' and assign_id is not null  "
			+ "  and nvl(cancel_Assign_flag,'N') <> 'Y'  and  "
			+ "  (:assignId is null or assign_id = :assignId)  "
			+ "  order by assign_id desc " , nativeQuery = true)
	List<GetRefAssignDto> getRefAssignId(@Param("assignId") String assignId );
	
	@Query(value = "select nvl(max(criteria_id),0) from dcc_criteria_master where mode_id = :modeId", nativeQuery = true)
	Long getMaxDccCriteriaId(@Param("modeId") String modeId);
	
	@Query(value = "select nvl(max(preassign_id), to_char(sysdate,'YYMM')||'0000') from dcc_criteria_history "
			+ "where mode_id = 'EM' and preassign_id like to_char(sysdate,'YYMM') || '%'", nativeQuery = true)
	Long getMaxPreAssignId();
	
	@Query(value = "SELECT"
			+ "	bill_accnt_num AS \"billAccNum\","
			+ "	service_num AS \"mobileNum\" "
			+ "FROM "
			+ "	("
			+ "	SELECT"
			+ "		bill_accnt_num,"
			+ "		service_num,"
			+ "		x_status_date,"
			+ "		max(a.x_status_date) OVER(PARTITION BY service_num) max_date "
			+ "	FROM"
			+ "		account_has_mobile a,"
			+ "		account ba "
			+ "	WHERE"
			+ "		service_num = :dccServiceNum "
			+ "		AND a.bill_accnt_num = ba.ou_num "
			+ "		AND ba.cust_stat_cd = 'Active' "
			+ "		AND (a.STATUS_CD = 'Active' "
			+ "			OR a.STATUS_CD LIKE 'Suspend%') "
			+ "	ORDER BY"
			+ "		a.x_status_date DESC, "
			+ "		a.last_upd DESC)"
			+ "WHERE "
			+ "	x_status_date = max_date "
			+ "	AND rownum <= 1", nativeQuery = true)
	DMSEM004GetBaByMobileNumDto getBaAccByMobileNum(@Param("dccServiceNum")String dccServiceNum);
	
	@Procedure(procedureName = "DCCP_LOAD_TEXT_EXEMPT")
	void dccLoadTextExempt(String modeId, String preAssignId);
}
